CREATE TABLE BANKING_T
(
bank_Name   VARCHAR(15),
bank_code   VARCHAR(15),
bank_Address  VARCHAR(50),
CONSTRAINT BANKING_PK PRIMARY KEY (bank_code)
);
CREATE TABLE BRANCHES_T
(
branch_ID  INTEGER,
branch_Name  VARCHAR(12),
branch_Address   VARCHAR(50),
CONSTRAINT BRANCHES_PK PRIMARY KEY (branch_ID)
);
CREATE TABLE ACCOUNT_T
(
Account_no INTEGER,
Account_type    VARCHAR(20),
Bal_amount     INTEGER,
CONSTRAINT ACCOUNT_PK PRIMARY KEY (Account_no)
);
CREATE TABLE CUSTOMER_T
(
Customer_ID   INTEGER,
Customer_Name    VARCHAR(12),
Customer_contact    INTEGER,
Customer_Address     VARCHAR(50),
CONSTRAINT CUSTOMER_PK PRIMARY KEY (Customer_ID)
);
CREATE TABLE LOAN_T
(
Loan_ID INTEGER,
Loan_type  VARCHAR(20),
Loan_Amount INTEGER,
CONSTRAINT LOAN_PK PRIMARY KEY (Loan_ID)
);
CREATE TABLE DEPOSIT_T
(
Deposit_ID INTEGER,
Deposit_type  VARCHAR(20),
Deposit_Amount INTEGER,
CONSTRAINT DEPOSIT_PK PRIMARY KEY (Deposit_ID)
);
CREATE TABLE WITHDRAW_T
(
Withdraw_ID INTEGER,
Withdraw_type  VARCHAR(20),
Withdraw_Amount INTEGER,
CONSTRAINT WITHDRAW_PK PRIMARY KEY (Withdraw_ID)
);
CREATE TABLE TRANSACTION_T
(
Tran_ID INTEGER,
Tran_type  VARCHAR(20),
Tran_Amount INTEGER,
CONSTRAINT TRANSACTION_PK PRIMARY KEY (Tran_ID)
);
CREATE TABLE EMPLOYEE_T
(
Employee_ID INTEGER,
Employee_Name  VARCHAR(20),
Employee_contact INTEGER,
Employee_Address VARCHAR(50),
CONSTRAINT EMPLOYEE_PK PRIMARY KEY (Employee_ID)
);
CREATE TABLE BALANCE_T
(
Bal_ID INTEGER,
Bal_Amount  INTEGER,
Customer_ID INTEGER,
CONSTRAINT BALANCE_PK PRIMARY KEY (Bal_ID),
CONSTRAINT BALANCE_FK FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER_T (Customer_ID)
);
CREATE TABLE CREDIT_CARD_T
(
Card_no INTEGER,
Account_no  INTEGER,
Card_Limit VARCHAR(10),
Expirydate  VARCHAR(15),
CONSTRAINT CREDIT_CARD_PK PRIMARY KEY (Card_no),
CONSTRAINT CREDIT_CARD_FK FOREIGN KEY (Account_no) REFERENCES ACCOUNT_T (Account_no)
);








